routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth:admin'],function () {

    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::resource('resources', 'ResourcesController');
    Route::resource('countries', 'CountryController');
    Route::resource('programs', 'ProgramController');
    Route::resource('services', 'ServiceController');

});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');

Route::post('login', 'Auth\LoginController@login')->name('admin.login.submit');

Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::get('/', 'AppController@index');
Route::get('/json/{countryID?}/{filterType?}/{tagID?}', 'AppController@generateResources');
Route::get('/test', 'AppController@generateResources');

//Route::get('social/login/redirect/{provider}', ['uses' => 'AppController@redirectToProvider', 'as' => 'social.login']);
//Route::get('social/login/{provider}', 'AppController@handleProviderCallback');
// Route::post('auth/facebookLogin/{offline?}', 'AppController@facebookLogin');

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable = ['id','name_en','name_ar','name_fr','slug'];
    protected $hidden = [
        'created_at', 'updated_at'
    ];
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers;

namespace App\Http\Controllers\Admin;

use App\Models\Service;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ServiceController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index()
    {
        $services = Service::all();
        return view('admin.services.index')->with([
            'services' => $services
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $service = new Service();


        $service->name_en = $request->name_en;
        $service->name_fr = $request->name_fr;
        $service->name_ar = $request->name_ar;
        $service->slug = $request->slug;

        if($service->save()){
            return $this->index();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(Service $service)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $service = Service::Where('id', $id)->first();

        return view('admin.services.edit')->with([
            'service' => $service,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $service = Service::find($id);

        $service->name_en = $request->name_en;
        $service->name_fr = $request->name_fr;
        $service->name_ar = $request->name_ar;
        $service->slug = $request->slug;

        if($service->save()){
            return $this->index();
        }


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $service = Service::find($id);
        $service->delete();
        return back();

    }
}

resources/views/admin/services/create.blade.php
@extends('admin.app')

@section('content')

    <!-- Breadcrumb -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" target="_blank">Website</a></li>
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>
    <!-- ./Breadcrumb -->

    <!-- container-fluid -->
    <div class="container-fluid">


        <div class="animated fadeIn">

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <strong>Add New </strong>Service
                        </div>
                        <div class="card-block col-md-8 col-md-offset-2">
                            <form action="{{ route('services.store') }}" method="post" class="form-horizontal">
                                {!! csrf_field() !!}
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_en">Name EN</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_en" name="name_en" class="form-control"
                                               placeholder="Name EN">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_fr">Name FR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_fr" name="name_fr" class="form-control"
                                               placeholder="Name FR">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_ar">Name AR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_ar" name="name_ar" class="form-control"
                                               placeholder="Name AR">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="slug">Slug</label>
                                    <div class="col-md-9">
                                        <textarea type="text" id="slug" name="slug"
                                                  class="form-control" placeholder="Slug"></textarea>
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


        </div>
        <!-- /.container-fluid -->
@endsection

resources/views/admin/services/edit.blade.php
@extends('admin.app')

@section('content')

    <!-- Breadcrumb -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" target="_blank">Website</a></li>
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>
    <!-- ./Breadcrumb -->

    <!-- container-fluid -->
    <div class="container-fluid">

        <div class="animated fadeIn">

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <strong>Add New </strong>Resource
                        </div>
                        <div class="card-block">
                            <form action="{{ action('Admin\ServiceController@update', $service['id']) }}"
                                  method="post" class="form-horizontal">
                                {!! csrf_field() !!}
                                {{ method_field('PUT') }}
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_en">Name EN</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_en" name="name_en" class="form-control"
                                               placeholder="Name EN" value="{{ $service->name_en }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_fr">Name FR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_fr" name="name_fr" class="form-control"
                                               placeholder="Name FR" value="{{ $service->name_fr }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_ar">Name AR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_ar" name="name_ar" class="form-control"
                                               placeholder="Name AR" value="{{ $service->name_ar }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="slug">Slug</label>
                                    <div class="col-md-9">
                                        <input type="text" id="slug" name="slug" class="form-control"
                                               placeholder="Slug"
                                               value="{{ $service->slug }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-sm btn-primary"><i
                                                class="fa fa-dot-circle-o"></i> Submit
                                    </button>
                                    <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
@endsection

resources/views/admin/services/index.blade.php
@extends('admin.app')

@section('content')

    <!-- Breadcrumb -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" target="_blank">Website</a></li>
        <li class="breadcrumb-item active">List Services</li>
    </ol>
    <!-- ./Breadcrumb -->

    <!-- container-fluid -->
    <div class="container-fluid">


        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            List Services
                        </div>
                        <div class="btn">
                            <a class="btn btn-success" href="{{ route('services.create') }}"> + Add Services </a>
                        </div>
                        <div class="card-block">
                            <table class="table table-responsive table-hover table-outline mb-0">
                                <thead class="thead-default">
                                <tr>
                                    <th class="text-center">Name En</th>
                                    <th class="text-center">Name Fr</th>
                                    <th class="text-center">Name Ar</th>
                                    <th class="text-center">Slug</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($services as $key => $service)
                                    <tr>
                                        <td class="text-center">{{ $service->name_en }}</td>
                                        <td class="text-center">{{ $service->name_fr }}</td>
                                        <td class="text-center">{{ $service->name_ar }}</td>
                                        <td class="text-center">{{ $service->slug }}</td>
                                        <td><a href="{{action('Admin\ServiceController@edit', $service['id'])}}"
                                               class="btn btn-warning">Edit</a>
                                            <hr>
                                            <form action="{{action('Admin\ServiceController@destroy', $service['id'])}}"
                                                  method="post">
                                                {{csrf_field()}}
                                                <label><input type="checkbox" name="_method" value="DELETE" required="true"> Confirm </label>
                                                <button class="btn btn-danger" type="submit">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--/.col-->
            </div>
            <!--/.row-->
        </div>


    </div>
    <!-- /.container-fluid -->
@endsection