routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth:admin'],function () {

    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::resource('resources', 'ResourcesController');
    Route::resource('countries', 'CountryController');
    Route::resource('programs', 'ProgramController');
    Route::resource('services', 'ServiceController');

});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');

Route::post('login', 'Auth\LoginController@login')->name('admin.login.submit');

Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::get('/', 'AppController@index');
Route::get('/json/{countryID?}/{filterType?}/{tagID?}', 'AppController@generateResources');
Route::get('/test', 'AppController@generateResources');

//Route::get('social/login/redirect/{provider}', ['uses' => 'AppController@redirectToProvider', 'as' => 'social.login']);
//Route::get('social/login/{provider}', 'AppController@handleProviderCallback');
// Route::post('auth/facebookLogin/{offline?}', 'AppController@facebookLogin');

app/Models/Program.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Program extends Model
{
    protected $fillable = ['id','name_en','name_ar','name_fr','slug'];
    protected $hidden = [
        'created_at', 'updated_at'
    ];
}

app/Http/Controllers/Admin/ProgramController.php
<?php

namespace App\Http\Controllers;

namespace App\Http\Controllers\Admin;

use App\Models\Program;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProgramController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index()
    {
        $programs = Program::all();
        return view('admin.programs.index')->with([
            'programs' => $programs
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.programs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $program = new Program();


        $program->name_en = $request->name_en;
        $program->name_fr = $request->name_fr;
        $program->name_ar = $request->name_ar;
        $program->slug = $request->slug;

        if($program->save()){
            return $this->index();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Program  $program
     * @return \Illuminate\Http\Response
     */
    public function show(Program $program)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Program  $program
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $program = Program::Where('id', $id)->first();

        return view('admin.programs.edit')->with([
            'program' => $program,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Program  $program
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $program = Program::find($id);

        $program->name_en = $request->name_en;
        $program->name_fr = $request->name_fr;
        $program->name_ar = $request->name_ar;
        $program->slug = $request->slug;

        if($program->save()){
            return $this->index();
        }


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Program  $program
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $program = Program::find($id);
        $program->delete();
        return back();

    }
}

resources/views/admin/programs/create.blade.php
@extends('admin.app')

@section('content')

    <!-- Breadcrumb -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" target="_blank">Website</a></li>
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>
    <!-- ./Breadcrumb -->

    <!-- container-fluid -->
    <div class="container-fluid">


        <div class="animated fadeIn">

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <strong>Add New </strong>Program
                        </div>
                        <div class="card-block col-md-8 col-md-offset-2">
                            <form action="{{ route('programs.store') }}" method="post" class="form-horizontal">
                                {!! csrf_field() !!}
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_en">Name EN</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_en" name="name_en" class="form-control"
                                               placeholder="Name EN">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_fr">Name FR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_fr" name="name_fr" class="form-control"
                                               placeholder="Name FR">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_ar">Name AR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_ar" name="name_ar" class="form-control"
                                               placeholder="Name AR">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="slug">Slug</label>
                                    <div class="col-md-9">
                                        <input type="text" id="slug" name="slug" class="form-control" placeholder="Slug">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-sm btn-primary"><i
                                                class="fa fa-dot-circle-o"></i> Submit
                                    </button>
                                    <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset
                                    </button>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/programs/edit.blade.php
@extends('admin.app')

@section('content')

    <!-- Breadcrumb -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" target="_blank">Website</a></li>
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>
    <!-- ./Breadcrumb -->

    <!-- container-fluid -->
    <div class="container-fluid">

        <div class="animated fadeIn">

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <strong>Edit </strong>Program
                        </div>
                        <div class="card-block">
                            <form action="{{ action('Admin\ProgramController@update', $program['id']) }}" method="post"
                                  class="form-horizontal">
                                {!! csrf_field() !!}
                                {{ method_field('PUT') }}
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_en">Name EN</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_en" name="name_en" class="form-control"
                                               placeholder="Name EN" value="{{ $program->name_en }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_fr">Name FR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_fr" name="name_fr" class="form-control"
                                               placeholder="Name FR" value="{{ $program->name_fr }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_ar">Name AR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_ar" name="name_ar" class="form-control"
                                               placeholder="Name AR" value="{{ $program->name_ar }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="slug">Code
                                        Country : slug</label>
                                    <div class="col-md-9">
                                        <input type="text" id="slug" name="slug" class="form-control"
                                               placeholder="Slug / Code Country"
                                               value="{{ $program->slug }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-sm btn-primary"><i
                                                class="fa fa-dot-circle-o"></i> Submit
                                    </button>
                                    <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
@endsection

resources/views/admin/programs/index.blade.php
@extends('admin.app')

@section('content')

    <!-- Breadcrumb -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" target="_blank">Website</a></li>
        <li class="breadcrumb-item active">List Programs</li>
    </ol>
    <!-- ./Breadcrumb -->

    <!-- container-fluid -->
    <div class="container-fluid">


        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            List Programs
                        </div>
                        <div class="btn">
                            <a class="btn btn-success" href="{{ route('programs.create') }}"> + Add Programs </a>
                        </div>
                        <div class="card-block">
                            <table class="table table-responsive table-hover table-outline mb-0">
                                <thead class="thead-default">
                                <tr>
                                    <th class="text-center">Name En</th>
                                    <th class="text-center">Name Fr</th>
                                    <th class="text-center">Name Ar</th>
                                    <th class="text-center">Slug</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($programs as $key => $program)
                                    <tr>
                                        <td class="text-center">{{ $program->name_en }}</td>
                                        <td class="text-center">{{ $program->name_fr }}</td>
                                        <td class="text-center">{{ $program->name_ar }}</td>
                                        <td class="text-center">{{ $program->slug }}</td>
                                        <td><a href="{{action('Admin\ProgramController@edit', $program['id'])}}"
                                               class="btn btn-warning">Edit</a>
                                            <hr>
                                            <form action="{{action('Admin\ProgramController@destroy', $program['id'])}}"
                                                  method="post">
                                                {{csrf_field()}}
                                                <label><input type="checkbox" name="_method" value="DELETE" required="true"> Confirm </label>
                                                <button class="btn btn-danger" type="submit">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--/.col-->
            </div>
            <!--/.row-->
        </div>


    </div>
    <!-- /.container-fluid -->
@endsection