routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth:admin'],function () {

    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::resource('resources', 'ResourcesController');
    Route::resource('countries', 'CountryController');
    Route::resource('programs', 'ProgramController');
    Route::resource('services', 'ServiceController');

});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');

Route::post('login', 'Auth\LoginController@login')->name('admin.login.submit');

Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::get('/', 'AppController@index');
Route::get('/json/{countryID?}/{filterType?}/{tagID?}', 'AppController@generateResources');
Route::get('/test', 'AppController@generateResources');

//Route::get('social/login/redirect/{provider}', ['uses' => 'AppController@redirectToProvider', 'as' => 'social.login']);
//Route::get('social/login/{provider}', 'AppController@handleProviderCallback');
// Route::post('auth/facebookLogin/{offline?}', 'AppController@facebookLogin');

resources/views/admin/resources/create.blade.php
@extends('admin.app')

@section('content')

    <!-- Breadcrumb -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" target="_blank">Website</a></li>
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>
    <!-- ./Breadcrumb -->

    <!-- container-fluid -->
    <div class="container-fluid">


        <div class="animated fadeIn">

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <strong>Add New </strong>Resource
                        </div>
                        <div class="card-block col-md-8 col-md-offset-2">
                            <form action="{{ route('resources.store') }}" method="post" class="form-horizontal">
                                {!! csrf_field() !!}

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="title_en">Title EN</label>
                                    <div class="col-md-9">
                                        <input type="text" id="title_en" name="title_en" class="form-control"
                                               placeholder="Title EN">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="title_fr">Title FR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="title_fr" name="title_fr" class="form-control"
                                               placeholder="Title FR">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="title_ar">Title AR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="title_ar" name="title_ar" class="form-control"
                                               placeholder="Title AR">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="description_en">Description
                                        EN</label>
                                    <div class="col-md-9">
                                        <textarea type="text" id="description_en" name="description_en"
                                                  class="form-control" placeholder="Description EN"></textarea>
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="description_fr">Description
                                        FR</label>
                                    <div class="col-md-9">
                                        <textarea type="text" id="description_fr" name="description_fr"
                                                  class="form-control" placeholder="Description FR"></textarea>
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="description_ar">Description
                                        AR</label>
                                    <div class="col-md-9">
                                        <textarea type="text" id="description_ar" name="description_ar"
                                                  class="form-control" placeholder="Description AR"></textarea>
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="description_en">Link To File</label>
                                    <div class="col-md-9">
                                        <input type="text" id="link" name="link" class="form-control"
                                               placeholder="URL To File">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="country_slug">Country</label>
                                    <div class="col-md-9">
                                        <select id="country_slug" name="country_slug" class="form-control">
                                            <option value="" disabled selected>Choose Your Country</option>
                                            @foreach ($countries as $index=>$item)
                                                <option value="{{ $item->id }}">{{ $item->name_fr}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                {{--<div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="services">Services :</label>
                                    <div class="col-md-9">
                                        <select id="services" name="services[]" class="form-control" size="10"
                                                multiple="">
                                            <option value="" disabled>Choose Your services</option>
                                            @foreach ($services as $index=>$item)
                                                <option value="{{ $item->id }}">{{ $item->name_fr }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>--}}

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label">Check your services</label>
                                    <div class="col-md-9">
                                        @foreach ($services as $index=>$item)
                                            <label class="checkbox-inline" for="services{{ $item->id }}">
                                                <input type="checkbox" id="services{{ $item->id }}"
                                                       name="services[]" value="{{ $item->id }}"> {{ $item->name_fr }}
                                            </label>
                                        @endforeach
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label">Check your programs</label>
                                    <div class="col-md-9">
                                        @foreach ($programs as $index=>$item)
                                            <label class="checkbox-inline" for="programs{{ $item->id }}">
                                                <input type="checkbox" id="programs{{ $item->id }}"
                                                       name="programs[]" value="{{ $item->id }}"> {{ $item->name_fr }}
                                            </label>
                                        @endforeach
                                    </div>
                                </div>

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-sm btn-primary"><i
                                                class="fa fa-dot-circle-o"></i> Submit
                                    </button>
                                    <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset
                                    </button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>


        </div>
        <!-- /.container-fluid -->
@endsection

resources/views/admin/resources/edit.blade.php
@extends('admin.app')

@section('content')

    <!-- Breadcrumb -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" target="_blank">Website</a></li>
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>
    <!-- ./Breadcrumb -->

    <!-- container-fluid -->
    <div class="container-fluid">

        <div class="animated fadeIn">

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <strong>Edit </strong>Resource
                        </div>
                        <div class="card-block">
                            <form action="{{ action('Admin\ResourcesController@update', $resource['id']) }}" enctype="multipart/form-data" method="post" class="form-horizontal">
                                {!! csrf_field() !!}
                                {{ method_field('PUT') }}
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="title_en">Title EN</label>
                                    <div class="col-md-9">
                                        <input type="text" id="title_en" name="title_en" class="form-control"
                                               placeholder="Title EN" value="{{ $resource->title_en }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="title_fr">Title FR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="title_fr" name="title_fr" class="form-control"
                                               placeholder="Title FR" value="{{ $resource->title_fr }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="title_ar">Title AR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="title_ar" name="title_ar" class="form-control"
                                               placeholder="Title AR" value="{{ $resource->title_ar }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="description_ar">Description
                                        AR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="description_ar" name="description_ar"
                                               class="form-control" placeholder="Description AR" value="{{ $resource->description_ar }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="description_fr">Description
                                        FR</label>
                                    <div class="col-md-9">
                                        <input type="text" id="description_fr" name="description_fr"
                                               class="form-control" placeholder="Description FR" value="{{ $resource->description_fr }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="description_en">Description
                                        EN</label>
                                    <div class="col-md-9">
                                        <input type="text" id="description_en" name="description_en"
                                               class="form-control" placeholder="Description EN" value="{{ $resource->description_en }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="description_en">Link To File</label>
                                    <div class="col-md-9">
                                        <input type="text" id="link" name="link" class="form-control"
                                               placeholder="URL To File" value="{{ $resource->link }}">
                                        <!--<span class="help-block">bla bla bla</span>-->
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="country_slug">Country</label>
                                    <div class="col-md-9">
                                        <select id="country_slug" name="country_slug" class="form-control">
                                            @foreach ($countries as $index=>$item)
                                                @if( $item->id == $resource->country_slug )
                                                    <option value="{{ $item->id }}" selected>{{ $item->name_fr }}</option>
                                                @else
                                                    <option value="{{ $item->id }}">{{ $item->name_fr }}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label">Check your services</label>
                                    <div class="col-md-9">
                                        @foreach ($services as $index=>$item)
                                            @if(in_array($item->id, $resource->services))
                                                <label class="checkbox-inline" for="services{{ $item->id }}">
                                                    <input type="checkbox" id="services{{ $item->id }}" checked=""
                                                           name="services[]" value="{{ $item->id }}"> {{ $item->name_fr }}
                                                </label>
                                            @else
                                                <label class="checkbox-inline" for="inline-checkbox{{ $item->id }}">
                                                    <input type="checkbox" id="inline-checkbox{{ $item->id }}"
                                                           name="services[]" value="{{ $item->id }}"> {{ $item->name_fr }}
                                                </label>
                                            @endif
                                        @endforeach
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label">Check your programs</label>
                                    <div class="col-md-9">
                                        @foreach ($programs as $index=>$item)
                                            @if(in_array($item->id, $resource->programs))
                                                <label class="checkbox-inline" for="inline-checkbox{{ $item->id }}">
                                                    <input type="checkbox" id="inline-checkbox{{ $item->id }}" checked=""
                                                           name="programs[]" value="{{ $item->id }}"> {{ $item->name_fr }}
                                                </label>
                                            @else
                                                <label class="checkbox-inline" for="programs{{ $item->id }}">
                                                    <input type="checkbox" id="programs{{ $item->id }}"
                                                           name="programs[]" value="{{ $item->id }}"> {{ $item->name_fr }}
                                                </label>
                                            @endif
                                        @endforeach
                                    </div>
                                </div>

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-sm btn-primary"><i
                                                class="fa fa-dot-circle-o"></i> Submit
                                    </button>
                                    <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset
                                    </button>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/resources/index.blade.php
@extends('admin.app')

@section('content')

    <!-- Breadcrumb -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" target="_blank">Website</a></li>
        <li class="breadcrumb-item active">Liste Resources</li>
    </ol>
    <!-- ./Breadcrumb -->

    <!-- container-fluid -->
    <div class="container-fluid">


        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            List Resources
                        </div>
                        <div class="btn">
                            <a class="btn btn-success" href="{{ route('resources.create') }}"> + Add Resources </a>
                        </div>
                        <div class="card-block">
                            <table class="table table-responsive table-hover table-outline mb-0">
                                <thead class="thead-default">
                                <tr>
                                    <th class="text-center" width="">Title Anglais</th>
                                    <th class="text-center">Description</th>
                                    <th class="text-center" width="50">Country</th>
                                    <th class="text-center" width="200">link</th>
                                    <th class="text-center" width="100">Services</th>
                                    <th class="text-center" width="80">Programs</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($resources as $key => $resource)
                                    <tr>
                                        <td><h6>{{ $resource->title_en }}</h6></td>
                                        <td>{{  str_limit( $resource->description_en, $limit = 150, $end = '...' ) }}</td>
                                        <td class="text-center">{{ $resource->country_slug }}</td>
                                        <td class="text-center" width="200">{{  str_limit( $resource->link, $limit = 20, $end = '...' ) }}</td>
                                        <td class="text-center">{{ $resource->services }}</td>
                                        <td class="text-center">{{ $resource->programs }}</td>
                                        <td><a href="{{action('Admin\ResourcesController@edit', $resource['id'])}}"
                                               class="btn btn-warning">Edit</a>
                                            <hr>
                                            <form action="{{action('Admin\ResourcesController@destroy', $resource['id'])}}"
                                                  method="post">
                                                {{csrf_field()}}
                                                <label><input type="checkbox" name="_method" value="DELETE" required="true"> Confirm </label>
                                                <button class="btn btn-danger" type="submit">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--/.col-->
            </div>
            <!--/.row-->
        </div>


    </div>
    <!-- /.container-fluid -->
@endsection